webpage/deepchat/models.py
"""app/models.py: Tutorial IV - Databases.

database models: collection of classes whose purpose is to represent the
                 data that we will store in our database.

The ORM layer (SQLAlchemy) will do the translations required to map
objects created from these classes into rows in the proper database table.
    - ORM: Object Relational Mapper; links b/w tables corresp. to objects.
"""

from deepchat import db
import json


class User(db.Model):
    """A model that represents our users.

    Jargon/Parameters:
        - primary key: unique id given to each user.
        - varchar: a string.
        - db.Column parameter info:
            - index=True: allows for faster queries by associating a given column
                          with its own index. Use for values frequently looked up.
            - unique=True: don't allow duplicate values in this column.

    Fields:
        id: (db.Integer) primary_key for identifying a user in the table.
        name: (str)
        posts: (db.relationship)

    """

    # Fields are defined as class variables, but are used by super() in init.
    # Pass boolean args to indicate which fields are unique/indexed.
    # Note: 'unique' here means [a given user] 'has only one'.
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)
    # Relationships are not actual database fields (not shown on a db diagram).
    # - backref: *defines* a field that will be added to the instances of
    #             Posts that point back to this user.
    # - lazy='dynamic': "Instead of loading the items, return another query
    #                    object which we can refine before loading items.
    conversations = db.relationship('Conversation', backref='user', lazy='dynamic')

    def __repr__(self):
        return "<User {0}>".format(self.name)


class Chatbot(db.Model):
    """Chatbot. Fields are the same as from yaml config files."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)  # TODO: make unique?
    dataset = db.Column(db.String(64))
    base_cell = db.Column(db.String(64))
    encoder = db.Column(db.String(64))
    decoder = db.Column(db.String(64))
    learning_rate = db.Column(db.Float)
    num_layers = db.Column(db.Integer)
    state_size = db.Column(db.Integer)
    conversations = db.relationship('Conversation', backref='chatbot', lazy='dynamic')

    def __init__(self, name, **bot_kwargs):
        self.name = (name or 'Unknown Bot')
        self.dataset = bot_kwargs['dataset']
        self.base_cell = bot_kwargs['base_cell']
        self.encoder = bot_kwargs['encoder']
        self.decoder = bot_kwargs['decoder']
        self.learning_rate = bot_kwargs['learning_rate']
        self.num_layers = bot_kwargs['num_layers']
        self.state_size = bot_kwargs['state_size']


    def __repr__(self):
        return json.dumps("<Chatbot {0}>".format(self.name))


class Conversation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    start_time = db.Column(db.DateTime, index=True, unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    chatbot_id = db.Column(db.Integer, db.ForeignKey('chatbot.id'))
    turns = db.relationship('Turn', backref='conversation', lazy='dynamic')

    def __repr__(self):
        return '<Conversation between {0} and {1}>'.format(self.user_id, self.chatbot_id)


class Turn(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_message = db.Column(db.Text)
    chatbot_message = db.Column(db.Text)
    conversation_id = db.Column(db.Integer, db.ForeignKey('conversation.id'))

    def __repr__(self):
        return 'User: {0}\nChatBot: {1}'.format(
            self.user_message, self.chatbot_message)

webpage/deepchat/main/forms.py
"""apps/forms.py: """

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, \
    TextField, TextAreaField, HiddenField
from wtforms.validators import DataRequired, InputRequired
from wtforms.validators import ValidationError


def bad_chars(form, string_field):
    for c in r";'`":
        if c in string_field.data:
            raise ValidationError('DONT TYPE DAT')


class ChatForm(FlaskForm):
    """Creates a chat_form for users to enter input."""
    message = StringField('message', validators=[DataRequired()])
    submit = SubmitField('Submit')


class UserForm(FlaskForm):
    """Form for creating/editing a user."""
    name = StringField(label='name',
                       id='user-name',
        validators=[DataRequired(), bad_chars])
    submit = SubmitField(label='Submit')


class SentencePairForm(FlaskForm):
    input_sentence = StringField(
        label='input-sentence',
        id='input-sentence',
        validators=[DataRequired()])
    response_sentence = StringField(
        label='response-sentence',
        id='response-sentence',
        validators=[DataRequired()])
    submit = SubmitField(label='Submit')

webpage/deepchat/__init__.py
"""deepchat/__init__.py: Initialize session objects."""

import os
from flask import Flask
from flask_wtf import CSRFProtect
from flask_moment import Moment
from flask_restful import Resource, Api
from flask_basicauth import BasicAuth
from flask_pagedown import PageDown
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from config import config

csrf = CSRFProtect()
# Initialize our database.
db = SQLAlchemy()
# Nice thingy for displaying dates/times.
moment = Moment()
# Client-sdie Markdown-to-HTML converter implemented in JS.
pagedown = PageDown()
# Flask-restful api interface.
api = Api()
# Database visualizer.
#name=os.getenv('APPENGINE_CONFIG', 'Development').title(),
admin = Admin(template_mode='bootstrap3')
# Basic authentication (mainly for using flask-admin).
basic_auth = BasicAuth()

class ReverseProxied(object):
    '''Wrap the application in this middleware and configure the 
    front-end server to add these headers, to let you quietly bind 
    this to a URL other than / and to an HTTP scheme that is 
    different than what is used locally.

    In nginx:
    location /myprefix {
        proxy_pass http://192.168.0.1:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Script-Name /myprefix;
        }

    :param app: the WSGI application
    '''
    def __init__(self, app):
        self.app = app

    def __call__(self, environ, start_response):
        script_name = environ.get('HTTP_X_SCRIPT_NAME', '')
        if script_name:
            environ['SCRIPT_NAME'] = script_name
            path_info = environ['PATH_INFO']
            if path_info.startswith(script_name):
                environ['PATH_INFO'] = path_info[len(script_name):]

        scheme = environ.get('HTTP_X_SCHEME', '')
        if scheme:
            environ['wsgi.url_scheme'] = scheme

        server = environ.get('HTTP_X_FORWARDED_SERVER', '')
        if server:
            environ['HTTP_HOST'] = server

        return self.app(environ, start_response)


def create_app(config_name):
    """The application factory, which allows the app to be created at runtime. 
    This is in contrast to before, where it was created in the global scope 
    (i.e. no way to apply configuration changes dynamically).
    
    Returns:
        app: the created application instance. Note that the app is still 
        missing routes and custom error page handlers, which will be handled 
        by blueprints.
    """

    from .main import main as main_blueprint

    # Create flask application object, and
    # read/use info in config.py.
    app = Flask(__name__)
    #if config_name == 'production':
    #    app.wsgi_app = ReverseProxied(app.wsgi_app)

    csrf.init_app(app)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # Initialize our database.
    db.init_app(app)
    # Nice thingy for displaying dates/times.
    moment.init_app(app)
    # Client-sdie Markdown-to-HTML converter implemented in JS.
    pagedown.init_app(app)
    #
    admin.name = config_name.title()
    admin.init_app(app)

    basic_auth.init_app(app)

    api.init_app(app)
    app.register_blueprint(main_blueprint)

    return app

webpage/deepchat/main/__init__.py
"""Package constructor file for creating blueprint(s)."""

from flask import Blueprint
from flask_cors import CORS

# Blueprint(<blueprint name>, <module/package where blueprint is located>).
# Note: The <blueprint name> (main for us) defines the blueprint namespace.
main = Blueprint('main', __name__)
CORS(main, supports_credentials=True)

# By importing views and errors here, we cause the routes and error handlers
# to be associated with the blueprint.
from . import views, errors

webpage/deepchat/main/views.py
from datetime import datetime
import os
import yaml
import json

from flask import make_response, flash
from werkzeug.exceptions import HTTPException
from flask_admin.contrib import sqla

from . import main
from .. import db, web_bot, admin, basic_auth, api

from flask import redirect, current_app
from flask import render_template
from flask import session, url_for, request
from flask_cors import cross_origin
from flask_restful import Resource, fields

from .forms import ChatForm, UserForm
from ..models import User, Chatbot, Conversation, Turn
from .. import models
from pydoc import locate


@main.context_processor
def inject_enumerate():
    return dict(enumerate=enumerate)


@main.before_app_first_request
def load_gloabal_data():
    """Create the cornell_bot to be used for chat session."""
    session['start_time'] = None


@main.route('/')
@main.route('/index')
@cross_origin()
def index():
    # Create the (empty) forms that user can fill with info.
    user_form = UserForm()
    chat_form = ChatForm()
    return render_template('index.html',
                           user=session.get('user'),
                           user_form=user_form,
                           chat_form=chat_form)


@main.route('/about')
@cross_origin()
def about():
    return render_template('about.html', user=session.get('user', 'Anon'))


@main.route('/plots')
def plots():
    return render_template('plots.html',
                           user=session.get('user', 'Anon'))


def update_database(user_message, bot_response):
    """Fill database (db) with new input-response, and associated data."""

    # 1. Get the User db.Model.
    user = get_database_model('User', filter=session.get('user', 'Anon'))

    # 2. Get the Chatbot db.Model.
    bot_name = ChatAPI.bot_name
    chatbot = get_database_model('Chatbot', filter=bot_name)

    # 3. Get the Conversation db.Model.
    if session.get('start_time') is None:
        session['start_time'] = datetime.utcnow()
    conversation = get_database_model('Conversation',
                                      filter=session.get('start_time'),
                                      user=user,
                                      chatbot=chatbot)

    # 4. Get the Turn db.model. (called get adds it to the db if not there).
    _ = get_database_model('Turn',
                           user_message=user_message,
                           chatbot_message=bot_response,
                           conversation=conversation)
    db.session.commit()


def get_database_model(class_name, filter=None, **kwargs):
    model_class = getattr(models, class_name)
    assert model_class is not None, 'db_model for %s is None.' % class_name

    if filter is not None:
        if class_name == 'Conversation':
            filter_kw = {'start_time': filter}
        else:
            filter_kw = {'name': filter}
        db_model = model_class.query.filter_by(**filter_kw).first()
    else:
        db_model = None
        filter_kw = {}

    if db_model is None:
        db_model = model_class(**filter_kw, **kwargs)
        db.session.add(db_model)
    return db_model


# -------------------------------------------------------
# APIs
# -------------------------------------------------------

class UserAPI(Resource):

    def post(self):
        name = request.values.get('name', 'Anon')
        session['user'] = name
        user_model = get_database_model('User', filter=name)
        return {'name': user_model.name}


class ChatAPI(Resource):
    # Class attributes. This is convenient since we only want one active
    # bot at any given time.
    bot_name = 'Unk Bot'
    bot = None

    def __init__(self, data_name):
        if ChatAPI.bot_name != data_name:
            ChatAPI.bot_name = data_name
            ChatAPI.bot = web_bot.FrozenBot(frozen_model_dir=data_name,
                                            is_testing=current_app.testing)
            config = ChatAPI.bot.config
            _ = get_database_model('Chatbot',
                                   filter=ChatAPI.bot_name,
                                   dataset=config['dataset'],
                                   **config['model_params'])
            db.session.commit()
            # TODO: delete this after refactor rest of file.
            session['data_name'] = data_name

    def post(self):
        print('post received')
        print('request:', request)
        user_message = request.values.get('user_message')
        print('user_message = ', user_message)
        bot_response = self.bot(user_message)
        print('resp:', bot_response)
        update_database(user_message, bot_response)
        return {'response': bot_response,
                'bot_name': ChatAPI.bot_name}


class RedditAPI(ChatAPI):
    def __init__(self):
        super(RedditAPI, self).__init__('reddit')


class CornellAPI(ChatAPI):
    def __init__(self):
        super(CornellAPI, self).__init__('cornell')


class UbuntuAPI(ChatAPI):
    def __init__(self):
        super(UbuntuAPI, self).__init__('ubuntu')

api.add_resource(UserAPI, '/user/')
api.add_resource(RedditAPI, '/chat/reddit/')
api.add_resource(CornellAPI, '/chat/cornell/')
api.add_resource(UbuntuAPI, '/chat/ubuntu/')

# -------------------------------------------------------
# ADMIN: Authentication for the admin (me) on /admin.
# -------------------------------------------------------


class AuthException(HTTPException):
    def __init__(self, message):
        super().__init__(message, make_response(
            "You could not be authenticated. Please refresh the page.", 401,
            {'WWW-Authenticate': 'Basic realm="Login Required"'}))


class ModelView(sqla.ModelView):
    def is_accessible(self):
        if not basic_auth.authenticate():
            raise AuthException('Not authenticated.')
        else:
            return True

    def inaccessible_callback(self, name, **kwargs):
        return redirect(basic_auth.challenge())

admin.add_view(ModelView(User, db.session))
admin.add_view(ModelView(Chatbot, db.session))
admin.add_view(ModelView(Conversation, db.session))
admin.add_view(ModelView(Turn, db.session))

webpage/deepchat/templates/about.html
{%  extends  "base.html" %}
{% set active_page = "about" %}

{% block nav_session_user %}
<ul class="nav navbar-nav navbar-right">
<span id='nav-session-user' class="navbar-text">
  {% if user %}
    User: {{ user }}
  {% else %}
    User: Anon
  {% endif %}
</span>
</ul>
{% endblock nav_session_user %}



<!-- Chat Section -->
{% block page_content %}
  <div class="jumbotron">
    <h1>DeepChatModels</h1>
    <p>
      A small framework for building and playing with conversation models in TensorFlow.
    </p>
  </div>


  <div class="row">
    <div class="media">
      <div class="media-left media-top">
        <a href="#">
          <img src="https://avatars3.githubusercontent.com/u/11165945?v=3&s=460"
               class="img-rounded">
        </a>
      </div>

      <div class="media-body">

        <h2>About Me</h2>
        <p>
          I recently graduated (Dec 2016) from UC Berkeley, and now
          I spend my time working on personal projects like this, and also
          studying machine learning/data science/etc.
        </p>

        <hr>
        <h3>Links</h3>
        <a class="btn btn-social-icon btn-github"
           href="https://github.com/mckinziebrandon/DeepChatModels">
          <!--<i class="fa fa-github fa-2x" aria-hidden="true">GitHub</i>-->
          <span class="fa fa-github fa-5x"></span>
        </a>

      </div>
    </div>
  </div>

{% endblock page_content %}

webpage/deepchat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- block head:
    - defines the head element for this html file and can be used by all children.
    - Children can either override or add to it.
    - See index.html for a simple example. -->
  {% block head %}

    {% block metas %}
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="sentient-machine">
    {% endblock metas %}

    <title>
      {% block title %}
        Deep Chat Models
      {% endblock title %}
    </title>

    <!-- Lil yelcornell_bot bot favicon -->
    <link href="/static/img/favicon.ico" rel="icon" type="image/x-icon">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" id="theme-link"
          href="{{ url_for('static', filename='css/lumen-bootstrap.min.css') }}">

    <!-- Custom styles for this template (I see ur overrule with an overrule. -->
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='css/theme.css') }}">

    <!-- Custom Fonts -->
    <link href="{{ url_for('static', filename='vendor/font-awesome/css/font-awesome.min.css') }}"
          rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
          rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script"
          rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700"
          rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet" type="text/css" >

    <!-- CSS Modifications -->
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='css/style_modifications.css') }}">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript"
            src="{{ url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js') }}"></script>

  {% endblock head %}
</head>

<body id="page-top" class="index">

<!-- Navigation -->
{% block navbar %}
  {%  set navigation_bar = [
        ('/', 'index', 'Home'),
        ('/plots', 'plots', 'Plots'),
        ('/about', 'about', 'About')
    ] -%}
  {%  set active_page = active_page|default('index') -%}

  <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          {% for _ in range(3) %}
            <span class="icon-bar"></span>
          {% endfor %}
        </button>
        <a class="navbar-brand" href="/">DeepChatModels</a>
      </div>

      <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav">
          {%  for href, id, caption in navigation_bar %}
            <li {% if id == active_page %} class="active" {% endif %}>
              <a href="{{ href|e }}">{{ caption|e }}</a>
            </li>
          {% endfor %}
        </ul>

        {% block nav_session_user %}
        <ul class="nav navbar-nav navbar-right">
        <span id='nav-session-user' class="navbar-text">
          <!-- user_form.js injects name of current user here -->
        </span>
        </ul>
        {% endblock nav_session_user %}

      </div>  <!-- end: navbar -->

    </div>  <!-- end: container -->
  </nav>
{% endblock navbar %}

<!-- Declare a block with name 'content' for derived templates. -->
{% block content %}
  <div class="container">
    <!-- Display any flash() message calls from e.g. views.py -->
    {%  with messages = get_flashed_messages() %}
      {%  if messages %}
        <div class="alert alert-info">
          {% for message in messages %}
            <p>{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}
  </div>  <!-- end: container -->

  <!-- Inject derived pages' content inside the following container. -->
  <div class="container">
    {% block page_content %}
    {% endblock page_content %}
  </div>
{%  endblock content %}


{% block scripts %}
  <!-- Recommended by flask docs. -->
  <script>
      var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
      var $INDEX_URL = "{{ url_for('main.index', _scheme='https', _external=True ) }}";
  </script>


  <!-- Latest Bootstrap JavaScript -->
  <script src="{{ url_for('static', filename='vendor/bootstrap-3.3.7-dist/js/bootstrap.min.js') }}"></script>

  <!-- Plugin JavaScript -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.easing.1.3.js') }}"></script>
  <!--<script src="{{ url_for('static', filename='vendor/plugins/tether.min.js') }}"></script>-->

  <!-- Contact Form JavaScript -->
  <script src="{{ url_for('static', filename='js/jqBootstrapValidation.js') }}">
  </script>


{% endblock scripts %}

</body>
</html>

webpage/deepchat/templates/index.html
{%  extends  "base.html" %}
{% set active_page = "index" %}
{% from "macros/forms.html" import render_chat_form, render_user_form %}

<!-- Chat Section -->
{% block page_content %}

  <div class="jumbotron">
    <h1>Conversation Models in TensorFlow</h1>
    <p>Have a chat with a deep neural network.</p>
  </div>


  <h2>Give Yourself a Nickname &nbsp;
    <button type="button" class="btn btn-xs btn-info"
            data-toggle="popover"
            title="&quot;Data&quot;"
            data-content="I'm slowly building a
              database of conversations, and it helps to
              have an identifier for the user (defaults to 'Anon').
              It can be anything!">
      Why?
    </button>
  </h2>

  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <p>
        The bot would like to know who it is talking to.
        Feel free to enter a nickname for yourself below:
      </p>

      <div class="row">
        {{ render_user_form(user_form, "user-form") }}
      </div>

    </div>
  </div>
  <br>

  <hr>
  <h2>Chat with a Bot</h2>

  <div class="row">
  <div class="col-xs-12 col-sm-10">
  <p>
  I've uploaded two simple models here that you can chat with. One was trained on
  the Cornell Movie Dialogs, the other on a subset (2007-2009) of the Reddit comments
  dataset. They both have the same model architecture. I'll upload the full configurations
  soon, but their key components are as follows:
  <ul>
  <li>Max sentence length: 10</li>
    <li>Vocabulary size: 40000</li>
    <li>BasicEncoder to BasicDecoder; single-layer each</li>
  </ul>
  The rest of the parameters (and some of the above) are the default values. They represent
  the simplest model(s) the project supports.
  </p>
  </div>
  </div>


  <div class="row">
    <div class="col-xs-12">
      <ul class="nav nav-tabs">
        {% for i, dataset_name in enumerate(['cornell', 'reddit', 'ubuntu']) %}
          <li role="presentation"
              data-target="#{{ dataset_name }}-chat-box"
              data-slide-to="{{ i }}">
            <a href="#"><span>{{ dataset_name | capitalize }}</span></a></li>
        {% endfor %}
      </ul>
    </div>
  </div>


  <div id="chat-carousel" class="carousel slide">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      {% for dataset_name in ['cornell', 'reddit', 'ubuntu'] %}
        <div id="{{ dataset_name }}-chat-box" class="chat-box item">
          <!-- chat box injected here -->
          <div id='{{ dataset_name }}-chat-log'
               class="chat-log col-xs-12 col-sm-10 col-sm-offset-1">
          </div>
          <!-- User input injected here -->
          {{ render_chat_form(chat_form, dataset_name+"-chat-form", dataset_name) }}
        </div>
      {% endfor %}
    </div> <!-- end: .carousel-inner -->

    <!-- Controls -->
    <a class="left carousel-control" href="#chat-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#chat-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <hr>
  <br><br>

{%  endblock page_content %}

{% block scripts %}
  {{ super() }}

  <script type="text/javascript">
      var csrf_token = "{{ csrf_token() }}";
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              console.log('this.crossDomain:', this.crossDomain);
              if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrf_token);
              }
          }
      });
  </script>

  <script>
      $(function() {
          $('[data-toggle="popover"]').popover();

          // Activate the carousel.
          //$('.carousel').carousel();
          $('#chat-carousel').carousel({interval: false});

          $('#cornell-chat-box').addClass('active');
          $('.nav-tabs li[data-target="#cornell-chat-box"]')
                  .addClass('active')
                  .find('span').addClass('text-primary');
          $('#chat-carousel').carousel({interval: 9999});

          // From carousel to nav-pills . . .
          $('#chat-carousel').on('slide.bs.carousel', function(event) {
              $('.nav-tabs li').removeClass('active');
              $('.nav-tabs li span').removeClass('text-primary');
              let activeTab = $('[data-target="#' + event.relatedTarget.id + '"]');
              activeTab.addClass('active');
              activeTab.find('span').addClass('text-primary');

              // TODO: Send a POST request to activate the chatbot, so we can
              // initialize/destroy them dynamically instead of all at once.
              });

              // From nav-pills to carousel . . .
              // Just simulates moving the carousel to the right index,
              // so we can put most of the behavior in that handler instead.
              $('.nav-tabs li').click(function(event) {
                  let index = $(this).data('slide-to');
                  $('#chat-carousel').carousel(index);
                  event.preventDefault();
              });

          });
      </script>

    <!-- Chat Processing JavaScript -->
  <script src="{{ url_for('static', filename='js/chat_processing.js') }}"></script>
  <script src="{{ url_for('static', filename='js/user_form.js') }}"></script>



    {% endblock scripts %}